### ISSUE TITLE
Custom symbols are centered in GUI but skewed on Web UI

### ISSUE THREAD

**Issue by g1augusto** [GNS3/gns3-web-ui#1019] opened 2020-12-16 09:27 UTC
Hi Jeremy, All,

I have some symbols that are correctly centered in the GUI but totally not in the WebUI, also one of them is strangely quite bigger than the others, is it something worth fixing?

![image](https://user-images.githubusercontent.com/26431888/102329856-29d7a580-3f89-11eb-9065-d26031460c60.png)

![image](https://user-images.githubusercontent.com/26431888/102329904-36f49480-3f89-11eb-9384-19801f781b76.png)

**Comment by piotrpekala7** [comment] 2020-12-16 10:32
@g1augusto Do you use latest version? Cause we had similar problems in previous versions and that should be solved

**Comment by g1augusto** [comment] 2020-12-16 21:53
Hi @piotrpekala7 

I am running the latest version

**Comment by piotrpekala7** [comment] 2020-12-16 23:16
ok I'm checking it

**Comment by piotrpekala7** [comment] 2020-12-16 23:59
I tested behavior of web UI with topology from the screenshot below.
![Capture](https://user-images.githubusercontent.com/31202938/102420616-d5710c00-4002-11eb-9bf6-15249d3638b5.JPG)

**Comment by piotrpekala7** [comment] 2020-12-17 00:03
@g1augusto please could you tell me which browser & os you use?
also can you tell me where these icons come from? then I could try to use them

**Comment by g1augusto** [comment] 2020-12-17 10:15
Browser
![image](https://user-images.githubusercontent.com/26431888/102473930-51e20a00-4058-11eb-9159-85862dd98972.png)

OS:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎11/‎2020
OS build	19042.685
Experience	Windows Feature Experience Pack 120.2212.551.0

These are some of my icons, the ones used in the topology and I made them myself
[icons.zip](https://github.com/GNS3/gns3-web-ui/files/5708540/icons.zip)

**Comment by piotrpekala7** [comment] 2021-01-08 00:45
I prepared quick fix for this solution here https://github.com/GNS3/gns3-web-ui/tree/Custom-symbols-are-centered-in-GUI-but-skewed-on-Web-UI but I'm not sure if it works in all scenarios

**Comment by piotrpekala7** [comment] 2021-02-01 21:06
@grossmj I verified this fix with 3 topologies, please let me know if you find sth not working

**Comment by grossmj** [comment] 2021-02-01 23:40
Ok, I will check.

**Comment by g1augusto** [comment] 2021-03-02 08:57
Hi Jeremy and Piotr,

Sorry for the late reply, I could not reply earlier than this.

I am running now version **2.2.18** and looks much better but still some mismatch between some icons size and lines draw, let me give you a screenshot

Windows application : 
![image](https://user-images.githubusercontent.com/26431888/109623348-57220180-7b3d-11eb-8f3d-a81e61ba4bc2.png)

Windows WebUI:
Chrome Version 88.0.4324.150 (Official Build) (64-bit) on 
Edition	Windows 10 Pro
Version	20H2
Installed on	‎10/‎11/‎2020
OS build	19042.804
Experience	Windows Feature Experience Pack 120.2212.551.0


![image](https://user-images.githubusercontent.com/26431888/109623507-7fa9fb80-7b3d-11eb-8629-a94acdac49f9.png)

**Comment by piotrpekala7** [comment] 2021-03-02 10:51
@g1augusto 

I'm not sure if we can additional conditions for rendering svg but we'll try. Could you please share me your project again? We would be very thankful!

**Comment by g1augusto** [comment] 2021-03-02 11:11
> @g1augusto
> 
> I'm not sure if we can additional conditions for rendering svg but we'll try. Could you please share me your project again? We would be very thankful!

Sure,

you mean the project file or the full project with VMs? I guess the latter option is hard to achieve as all these VMs reach up to 250+ GB in size all together.

**Comment by piotrpekala7** [comment] 2021-03-02 17:06
only project file

**Comment by warmichi** [comment] 2021-03-03 17:04
Hello,

we are facing the same problem.
Its working fine in the client but not in the web-ui.
https://www.gns3.com/community/featured/wrong-cable-alignment-on-custom-icons

**Comment by warmichi** [comment] 2021-03-04 12:21
my colleague has found out something interesting. If the icons are in the folder of the custom icons the problem appears. If the same icons are in the Built-IN icons folder it works.

![image](https://user-images.githubusercontent.com/18138795/109963258-7ca13d80-7cec-11eb-8136-144283a185e3.png)

**Comment by grossmj** [comment] 2021-03-04 13:07
Excellent finding, do you mind sharing this 128 symbol so we can be sure to replicate the problem? Thanks 👍

**Comment by piotrpekala7** [comment] 2021-03-05 17:21
I tested this symbol with some topologies and I'm not able to reproduce this error on 2.2.19

**Comment by piotrpekala7** [comment] 2021-03-05 17:22
![firefox](https://user-images.githubusercontent.com/31202938/110150512-a4bd9900-7ddf-11eb-826b-f9ee389a7ea9.PNG)
latest firefox, windows,

**Comment by piotrpekala7** [comment] 2021-03-05 17:23
![Chrome](https://user-images.githubusercontent.com/31202938/110150660-cae33900-7ddf-11eb-83c4-064b9d72de84.PNG)
latest chrome, windows

**Comment by piotrpekala7** [comment] 2021-03-05 17:30
in latest version we check if added svg icon has valid width property, if not we use default value
https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/widgets/node.ts#L96

**Comment by warmichi** [comment] 2021-03-05 18:49
Okay great we will update.

**Comment by g1augusto** [comment] 2021-03-10 12:49
Hi Again,

I had some time to bring online the project again and I have also update both GNS3 client and server to version 2.2.19, from my previous test on version 2.2.18 I see it's the same.

Let me attach the project file for you to look at it.
[Wireless_test.zip](https://github.com/GNS3/gns3-web-ui/files/6115887/Wireless_test.zip)

**Comment by piotrpekala7** [comment] 2021-03-25 20:42
We use d3js to create map for GNS3 project in web UI so we need to add default width and height for symbols that don't have this values cause if we don't do that svg won't render anything - unfortunately that's the reason for some issues with displaying symbols

**Comment by piotrpekala7** [comment] 2021-03-25 20:46
@grossmj did you have similar problems when it comes to symbols without width & height property in Qt? I checked GUI repo but I couldn't find that, maybe it's solved by framework

**Comment by grossmj** [comment] 2021-04-06 13:25
I couldn't reproduce. @warmichi can you post the symbols please? Thanks :+1:

**Comment by piotrpekala7** [comment] 2021-04-07 17:07
the reason is described in this task https://github.com/GNS3/gns3-web-ui/issues/1047, so if we fix this issue, icons will be centered correctly

**Closed by piotrpekala7** 2021-04-07 17:07 UTC
Labels: waiting for more information

**Comment by g1augusto** [comment] 2021-05-12 08:29
Sorry for replying so late but I had an opportunity now to test version 2.2.1 and I can see great improvements:

Only one object (cloud) seems to be skewed compared to the Windows GUI (where is centered correctly)

![image](https://user-images.githubusercontent.com/26431888/117943760-c6219080-b30c-11eb-9cc5-de6be6483d7c.png)


![image](https://user-images.githubusercontent.com/26431888/117943824-d2a5e900-b30c-11eb-9e3a-b3ef28be90ac.png)

**Comment by grossmj** [comment] 2021-05-16 12:41
Please can you post your cloud symbol here? (the svg file). Thanks :+1:
