### ISSUE TITLE
v3.0.0 alpha 3 - Can't add controller

### ISSUE THREAD

**Issue by spikefishjohn** [GNS3/gns3-web-ui#1438] opened 2023-02-11 16:11 UTC
I'm not sure what the correct way is to add a remote. I tried via the add controller page but it doesn't give any username/password options and just says reachable. 

![image](https://user-images.githubusercontent.com/31658656/218268560-a8553e5d-6826-4c49-9740-ea510a36c210.png)

![image](https://user-images.githubusercontent.com/31658656/218268589-6f075388-8ca0-4af1-83c2-d6814ed746fc.png)

**Comment by grossmj** [comment] 2023-03-21 11:44
There may be an issue with CORS. Have you started the web-ui in standalone mode or you connected directly to the bundled web-ui of the GNS3 server?

Please try to add the controller again and check if there is an error with the developer tools in your browser.

![Image](https://user-images.githubusercontent.com/4752614/226596359-f4d94c06-8024-45f9-8ec2-69fc30465c98.png)

Thanks!

**Comment by spikefishjohn** [comment] 2023-03-21 13:24
Not following on starting the webui in standalone mode. I just started gns3 server on both boxes and hit it on 3080. 

How do I start in standalone?

Will check for errors.

**Comment by spikefishjohn** [comment] 2023-03-30 00:22
CORS does seem like the problem.

![image](https://user-images.githubusercontent.com/31658656/228696849-92662775-db08-4d5d-9435-d275de226d23.png)

**Comment by spikefishjohn** [comment] 2023-03-30 00:24
Something else that is odd.. I can navigate to http://10.1.18.55:3080/static/web-ui/controllers without authenticating (opened in private mode). .56 is the other gns3 i'm trying to add.

**Comment by spikefishjohn** [comment] 2023-03-30 01:03
Is this a duplicate of [https://github.com/GNS3/gns3-web-ui/issues/1145](url)?

**Comment by grossmj** [comment] 2023-05-11 06:13
Is this a duplicate of https://github.com/GNS3/gns3-web-ui/issues/1145?

Yes, I think this is the same problem.

**Closed** 2023-06-23 07:09 UTC
