### ISSUE TITLE
[2.2.21] Unable to select multiple objects using mouse.

### ISSUE THREAD

**Issue by SairusCZ** [GNS3/gns3-web-ui#1141] opened 2021-05-16 16:10 UTC
It is currently only possible to select all objects in the topology by using CTRL+A. However, it is not possible to select multiple nodes/objects with mouse. 

Expected behavior:
1)Users should be able to select multiple objects by using mouse
2)User should be able to select multiple objects by holding down CTRL and clicking objects they want to select.
3)Overall the same behavior as in the QT client is expected. 

![node-selection](https://user-images.githubusercontent.com/24818591/118404130-d79ecb80-b671-11eb-99e3-b5e0e9153b9a.gif)

**Comment by piotrpekala7** [comment] 2021-05-17 18:33
This feature works fine in the latest version, it has been checked in both Chrome 90.0.4430.93 and Firefox 88.0.1. User is able to select multiple objects, also moving objects on topology works fine

**Comment by piotrpekala7** [comment] 2021-05-17 18:38
![screen-capture](https://user-images.githubusercontent.com/31202938/118539429-b6aca800-b74f-11eb-9bc7-fe0e201c770c.gif)

**Comment by piotrpekala7** [comment] 2021-05-17 22:31
Sorry, but we are unable to reproduce this error. 
Can you clarify the description?

**Comment by SairusCZ** [comment] 2021-05-18 08:33
I can reproduce it with:
Clients: Linux and Windows 10 clients with Chrome 90.0.4430.212 and Firefox 88.0.1. 
Server: Official GNS3 VM 2.2.21 (also on local GNS3 servers on Linux Manjaro, Linux Mint)


Can you confirm if the latest version of gns3-web-ui packaged with the gns3-server 2.2.21? When I go to http://<server_IP>/static/web-ui/help > release notes, I see "Current version: 2.2.19" and right bellow it "Current version: 2020.4.0-beta.1". 

![image](https://user-images.githubusercontent.com/24818591/118617864-52c3c700-b7c3-11eb-9d5c-2b7bb6684ad2.png)

**Comment by piotrpekala7** [comment] 2021-05-18 09:34
Current version is visible at the footer on servers, page, project page, preferences page...

**Comment by piotrpekala7** [comment] 2021-05-18 09:39
> 2)User should be able to select multiple objects by holding down CTRL and clicking objects they want to select.

maybe the problem is here? You don't have to press & hold ctrl key to select

**Comment by piotrpekala7** [comment] 2021-05-18 09:43
If you look in our selection manager https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/managers/selection-manager.ts, we do not distinguish behavior according to the system version, in fact we cannot detect it

**Comment by piotrpekala7** [comment] 2021-05-18 09:44
link to selection control: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/cartography/components/selection-control/selection-control.component.ts

**Comment by piotrpekala7** [comment] 2021-05-18 12:21
@SairusCZ 

I verified behavior also on Linux environment, did you apply any changes to js files?

**Comment by SairusCZ** [comment] 2021-05-18 20:25
> > 2)User should be able to select multiple objects by holding down CTRL and clicking objects they want to select.
> 
> maybe the problem is here? You don't have to press & hold ctrl key to select

To clarify, I meant holding down CTRL key while clicking on individual nodes in the topology. Let's say there are 3 routers next to each other in-line and the user only wants to select and move the two routers on the sides, while keeping the middle router in original place.

**Comment by SairusCZ** [comment] 2021-05-18 20:30
> @SairusCZ
> 
> I verified behavior also on Linux environment, did you apply any changes to js files?

@piotrpekala7 
I did not make any modification to GNS3. To be 100% sure, I reproduced it again with the bellow simple steps:

1)Download and deploy new GNS3 VM from https://github.com/GNS3/gns3-gui/releases/download/v2.2.21/GNS3.VM.VMware.ESXI.2.2.21.zip 
2)Connect the GNS3 web UI using Google Chrome in Incognito mode
3)Create a new blank project
4)Drop two Ethernet Hubs in the topology
5)There is no way for me to select the two Hubs and move them around with the mouse. The only exception is when I select everything with CTRL+A and then move the nodes around.

**Comment by piotrpekala7** [comment] 2021-05-18 21:30
@SairusCZ 

I'd really like to help you but still I'm not able to reproduce this error. Anyway, we don't use ctrl+click to select node in web UI, you have selection tool (simply drawing selection area) but I believe you know how it works from your screenshot

**Comment by piotrpekala7** [comment] 2021-05-18 21:31
@SairusCZ 

Do you have any another questions when it comes to selection tool?

**Comment by cristian-ciobanu** [comment] 2021-05-18 22:01
I confirm I have experienced the same issue as @SairusCZ but I also found something else.

Running the latest GNS3 2.2.21 server and GUI on same Linux system (Web-UI running on latest Chrome 90.0.4430.212)

On the left toolbar the first icon called **Selection Mode** when I click on it and the select some nodes on the topology it selects all of them and when I try to move them by clicking on one of the selected nodes, automatically it deselects all the other nodes and I can move only the active node on which I clicked when trying to move the whole selection of nodes.

Also as @SairusCZ  mentioned when using Ctrl + A to select all nodes I can move them around.

Instead when I click on the second icon on the left toolbar called **Pan Workspace** the whole topology is moving without selecting any node whenever I click on an empty space in on the topology.

I do not know if this is the intended behaviour or it is a bug regarding the **Pan Workspace** button.

**Comment by piotrpekala7** [comment] 2021-05-18 22:43
@cristian-ciobanu 

Yes, when it comes to 'Pan workspace' it should work as you describe it. It's FEATURE not bug... ;-)

**Comment by piotrpekala7** [comment] 2021-05-18 22:48
@cristian-ciobanu 

It's not possible to send the request with non integer value, look here: https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/node.service.ts#L73. We round **every** value for node position and also **every** value for link position https://github.com/GNS3/gns3-web-ui/blob/master/src/app/services/link.service.ts#L66

**Comment by piotrpekala7** [comment] 2021-05-18 22:53
@SairusCZ @cristian-ciobanu 

Could be so kind to help me find a bug with selection of multiple nodes? I added links to SelectionComponent and SelectionManager above, as I mentioned before and as you see on the screenshot I attached everything works fine on my environment and I'm not able to reproduce it so it will be great if you can help me determine where the problem is

**Comment by piotrpekala7** [comment] 2021-05-19 19:10
@SairusCZ @cristian-ciobanu 

Hi, did you find any more information regarding this issue?

**Comment by dorotazzz** [comment] 2021-05-20 09:56
![snap](https://user-images.githubusercontent.com/84460523/118959017-37db8900-b962-11eb-9c63-69e4c110067d.PNG)

I use web ui and I have nearly the same topology, everything works if you select objects properly, I don't use ctrl button cause I see it's not included in implementation

**Comment by piotrpekala7** [comment] 2021-05-20 09:58
@dorotazzz 
Have you checked that on latest release or developer version?

**Comment by dorotazzz** [comment] 2021-05-20 09:58
2.2.22, latest Chrome && FF

**Comment by piotrpekala7** [comment] 2021-05-20 09:59
@dorotazzz 
Ok, thanks for confirmation!

**Comment by MichaelRadke** [comment] 2021-05-20 10:03
no issues in multiple selection in 2.2.22dev

**Comment by piotrpekala7** [comment] 2021-05-20 10:04
@SairusCZ 
Did you check dev version 2.2.22?

**Comment by SairusCZ** [comment] 2021-05-20 13:20
@piotrpekala7 , I confirm that 2.2.22dev works for me as well. Thanks a lot!

![working_2 21 22dev](https://user-images.githubusercontent.com/24818591/118985496-c78f3080-b97e-11eb-8428-e0253a4ddf12.gif)

**Comment by piotrpekala7** [comment] 2021-05-20 13:22
@SairusCZ 
great, thanks for confirmation!

**Closed by piotrpekala7** 2021-05-20 13:22 UTC
Labels: waiting for more information
