### ISSUE TITLE
JSON schema error when moving link labels on the topology

### ISSUE THREAD

**Issue by cioby23** [GNS3/gns3-web-ui#891] opened 2020-06-18 08:44 UTC
OS: Linux (ArchLinux)
GNS3 web-ui:  v2020.2.0-beta.5

I have created a simple topology with two vIOS L2 switches connected with dual links between them and when I click on any of the interface labels and try to arrange them after I release the mouse button the below API error appears:

![image](https://user-images.githubusercontent.com/7124193/84998798-fabab580-b158-11ea-8c03-9802bc4f3572.png)

**Comment by piotrpekala7** [comment] 2020-06-18 09:03
@cioby23 this error says that the updated x position is invalid, it should have integer type (37 instead of 37.000...)

**Comment by grossmj** [comment] 2020-06-19 05:42
Looks like it comes from the interface labels being displayed. I will try to see if I can reproduce that problem.

**Comment by piotrpekala7** [comment] 2020-06-23 10:16
fixed in https://github.com/GNS3/gns3-web-ui/commit/206242dba98fa11e97882660820425e2689cca7b

**Closed by piotrpekala7** 2020-06-23 10:16 UTC
Labels: bug
